name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub get
        working-directory: example
      - run: flutter analyze
      - run: flutter analyze
        working-directory: example
