name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: beta
      - run: flutter analyze
      - run: flutter analyze
        working-directory: example
